USE goldenx;

CREATE TABLE IF NOT EXISTS settings (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    status_wheel TINYINT(1) NOT NULL DEFAULT 0,
    shoot_bank DECIMAL(16,2) NOT NULL DEFAULT 0,
    shoot_profit DECIMAL(16,2) NOT NULL DEFAULT 0,
    group_id VARCHAR(255) NULL,
    tg_id VARCHAR(255) NULL,
    tg_bot_id VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS system_dep (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NULL,
    min_sum DECIMAL(16,2) NOT NULL DEFAULT 0,
    comm_percent DECIMAL(8,2) NOT NULL DEFAULT 0,
    img VARCHAR(255) NULL,
    color VARCHAR(32) NULL,
    ps TINYINT UNSIGNED NOT NULL DEFAULT 0,
    number_ps VARCHAR(255) NULL,
    off TINYINT(1) NOT NULL DEFAULT 0,
    sort INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS system_withdraw (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NULL,
    min_sum DECIMAL(16,2) NOT NULL DEFAULT 0,
    comm_percent DECIMAL(8,2) NOT NULL DEFAULT 0,
    comm_rub DECIMAL(16,2) NOT NULL DEFAULT 0,
    img VARCHAR(255) NULL,
    color VARCHAR(32) NULL,
    off TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payments (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL DEFAULT 0,
    login VARCHAR(255) NULL,
    avatar VARCHAR(255) NULL,
    sum DECIMAL(16,2) NOT NULL DEFAULT 0,
    data VARCHAR(255) NULL,
    transaction VARCHAR(255) NULL,
    beforepay DECIMAL(16,2) NOT NULL DEFAULT 0,
    afterpay DECIMAL(16,2) NOT NULL DEFAULT 0,
    status TINYINT UNSIGNED NOT NULL DEFAULT 0,
    percent DECIMAL(8,2) NOT NULL DEFAULT 0,
    img_system VARCHAR(255) NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS withdraws (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL DEFAULT 0,
    login VARCHAR(255) NULL,
    avatar VARCHAR(255) NULL,
    ps VARCHAR(255) NULL,
    wallet VARCHAR(255) NULL,
    mult TINYINT UNSIGNED NOT NULL DEFAULT 0,
    sum DECIMAL(16,2) NOT NULL DEFAULT 0,
    sum_full DECIMAL(16,2) NOT NULL DEFAULT 0,
    date VARCHAR(255) NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 0,
    img_system VARCHAR(255) NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO settings (id) VALUES (1)
ON DUPLICATE KEY UPDATE id = id;
