USE goldenx;

CREATE TABLE IF NOT EXISTS settings (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    status_wheel TINYINT(1) NOT NULL DEFAULT 0,
    group_id VARCHAR(255) NULL,
    tg_id VARCHAR(255) NULL,
    tg_bot_id VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS system_dep (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    off TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS system_withdraw (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    off TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO settings (id) VALUES (1)
ON DUPLICATE KEY UPDATE id = id;
